enum MessageEnum {
  SERVERE_THINNESS("SERVERE_THINNESS"),
  MODERATE_THINNESS("MODERATE_THINNESS"),
  LIGTH_THINNESS("LIGTH_THINNESS"),
  HEALTHY("HEALTHY"),
  OVERWEIGHT("OVERWEIGHT"),
  OBESITY_GRADE_1("OBESITY_GRADE_1"),
  OBESITY_GRADE_2("OBESITY_GRADE_2"),
  OBESITY_GRADE_3("OBESITY_GRADE_3");

  final String value;

  const MessageEnum(this.value);
}
